apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kostis-codefresh/application-dependency-argocd.git
    targetRevision: HEAD
    path: ./manifests
   
  destination:
    server: https://kubernetes.default.svc
    namespace: my-api

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true 
  
